name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node:
          - 10
          - 12
          - 14

    runs-on: ubuntu-latest

    steps:
      # Setup the local repo
      - uses: actions/checkout@v1

      # Setup Node.js with the correct version
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      # Install dependencies
      - run: npm ci

      # Run tests
      - run: npm test
